### PR TITLE
Remove message not to disclose full path in the browser.

### PR DESCRIPTION
**Pull request by kappezoro**
When displayed file path in the browser, it might be happened directly traversal. 
The concern I mentioned is disclosing server side path can be found the file path by hacker (ex. /usr/local/xxx/xxx/.) it provide the hint to access directory/file.
So I will send this pull request not to display file path. 

And the response code should not be 200 since actually it's not OK. Logger also put message as Internal Server Error. So I will request also to change from 200 to 500 when Ruby has exception by loading Javascript/CSS.
Please confirm my pull request. Best Regards,

### CODE REVIEW

**Comment by rafaelfranca** [comment]
This pull request needs a rebase.

**Comment by kappezoro** [comment]
done.

**Comment by matthewd** [comment]
I think it's useful to show the full error in development. Setting aside the fact that running Sprockets::Server in production is (I believe?) discouraged, I do agree we should be more circumspect if something goes wrong in that situation.

But then I don't think we should even be mentioning the exception class.

And what about CSS errors?

**Comment by kappezoro** [comment]
You're right and agree with adopting to CSS and also removing excepction class.  Let me change to remove also exception class and adopt to CSS.

**Comment by kappezoro** [comment]
I revised like this https://github.com/kappezoro/sprockets/commit/ae46367b69d0ff7de7da744c17c61c9ed685fdd4
putting just String 'Internal Server Error'. 
If you have concerns, please let me know.  i will also update failed tests. thank you for reviewing.

**Comment by kappezoro** [comment]
done again.

**Comment by rafaelfranca** [comment]
This will make harder to debug in development. Can we add an option to enable the previous behavior?

**Comment by kappezoro** [comment]
We can debug them by checking log. the error description is same as previous in browser.
https://github.com/kappezoro/sprockets/blob/2b55eb792623399d757c7712ac468947c216fa15/lib/sprockets/server.rb#L86
Is it hard?

**Comment by schneems** [comment]
Since it's not documented. I'm thinking that server.rb shouldn't be used in production maybe only used as a reference implementation. I can write that down sometime.

If we want to ship this, I would make it conditional on `RACK_ENV`. While you __can__ use the logs to debug the problem, we should make an extended effort to make debugging problems in dev as easy as possible.

**Pull request closed without merging**
