### PR TITLE
[close #221] Favor charset from processor

### PR DESCRIPTION
**Pull request by schneems**
If a charset is returned by a pre-processor use it instead of automatically assigning one. This is needed so that non-gzippable assets will not accidentally be assigned a charset and gzipped later.

We're also removing a hash allocation needed for `Hash.merge!`.

### CODE REVIEW

**Comment by iggant** [comment]
looks great, 
will you also backport this patch to 3.x branch?

**Comment by schneems** [comment]
Yes i'll backport to 3.x.

**Comment by iggant** [comment]
thank you

**Comment by rafaelfranca** [comment]
:shipit:

**Comment by schneems** [comment]
@iggant i'm pretty in the weeds right now. Can you cherry pick these two commits off of master and give me a PR to the 3.x branch? Once merged into 3.x branch I can cut a minor release.

**Comment by iggant** [comment]
@schneems 
sorry don't have time for that, you've already done this with https://github.com/rails/sprockets/pull/228

**Pull request merged**
