### PR TITLE
Add failing test for deeply nested logical_path

### PR DESCRIPTION
**Pull request by elia**
Hit this while upgrading some Opal processor code to 3.0.

### CODE REVIEW

**Comment by josh** [comment]
Hey @elia! 

Thanks for the failing test first. Always help me understand what we're talking about here.

But I think this is working as I would expected. When I ran this locally it returned `"corelib/core/hash/shared.js"`. No `/index.js`.

Its nothing specific to deep paths, but anytime you have a `index.js`, it prefers its shorthand form of just the directory name. Remember that `index.js` is special and means you can just `require corelib/core/hash/shared`.

I think in 2.x sometimes it returned `"corelib/core/hash/shared/index.js" and `"corelib/core/hash/shared.js"  depending on if the asset was loaded by a full filename or logical path. I wanted to always have a consistent logical path to avoid confusion. Well, I guess its still confusing no, heh.

Just wondering if this is causing any other unforeseen problems or if it just surprised you?

**Comment by elia** [comment]
Hey!

Yeah, was in doubt about my hunch on the deep path :)

The problem is that we use logical paths to parse Ruby requires at compile time before passing them to sprockets. In particular in this case the file is from rubyspec:

https://github.com/opal/rubyspec/blob/master/core/hash/shared/index.rb

The logical path is used here to expand the classical expand_path idiom in the first two lines

    require File.expand_path('../../../../spec_helper', __FILE__)
    require File.expand_path('../../fixtures/classes', __FILE__)

In this case `__FILE__` is replaced with the logical path and of course fails because it's one level above.

Here's the point passing logical path to the compiler:

https://github.com/opal/opal/blob/754d28768de0334bce73d548c336d1e8c77cc356/lib/opal/sprockets/processor.rb#L74

And here where the requires are expanded in the compiler:

https://github.com/opal/opal/blob/754d28768de0334bce73d548c336d1e8c77cc356/lib/opal/nodes/call.rb

Added some context so that you can have a better understanding and I can get better advice :stuck_out_tongue_winking_eye: 

I'm sure there are good use cases for the special index behavior too, but I wonder if it can be relegated just to the directive processor. Anyway having a logical path that includes `index` already available would be good too or I can extract it myself.

**Comment by josh** [comment]
> I'm sure there are good use cases for the special index behavior too, but I wonder if it can be relegated just to the directive processor.

The other thing that I like is that its used for the compiled name. So we have a `app/assets/javascript/frameworks/index.coffee` bundle with all sorts of requires. But when thats compiled to `public/` its always written out as `public/assets/frameworks-123abc.js`.

> In this case __FILE__ is replaced with the logical path and of course fails because it's one level above.

For this specific case, it seems like you'll always want the `.rb` extension too. That can be trimmed off in the logical path in some cases.

There should be the original `load_path` and `filename` around. I'd almost say `__FILE__ = filename.sub(load_path, "")`

**Comment by elia** [comment]
Thanks, going with `logical_path = context.filename.sub(/^#{context.root_path}/, '')` as `#root_path` works for both v2 and v3.

Now the only thing left is removing all extensions coming from processors for a given file. I could go with something like:

```rb
sprockets.engines.map{|ext,eng| ext if eng.default_mime_type == 'application/javascript'}
```

but I prefer to check with you first

**Pull request closed without merging**
