### PR TITLE
WIP: pass functions directly

### PR DESCRIPTION
**Pull request by ahorek**
this attempts to fix a problem with thread safety, see https://github.com/rails/sprockets/issues/581 for more context

fixes https://github.com/rails/sprockets/issues/633 https://github.com/sass/sassc-ruby/issues/133 https://github.com/sass/sassc-rails/issues/122 https://github.com/sass/sassc-rails/issues/58 https://github.com/rails/sprockets/issues/638 ...

there's a race condition between sassc_processor.rb and sassc_compressor.rb, both calls SassC::Engine with different functions.

WIP because it this depends on https://github.com/sass/sassc-ruby/pull/162

1/ no more segfaults even with concurrency enabled
2/ sass gem has the same problem, but the gem is deprecated, so it can't be fixed
3/ https://github.com/sass/sassc-rails will require a similar change

### CODE REVIEW

**Comment by glebm** [comment]
sassc 2.3.0 has been released

**Comment by glebm** [comment]
@ahorek I think we'd also need to replace the dependency on `sass` with a dependency on `sassc >= 2.3.0`

**Comment by schneems** [comment]
is this ready to merge or still WIP?

**Comment by ahorek** [comment]
well, since sassc 2.3 is out for 6 months, there's nothing else blocking this PR.

however, it's difficult to write a reliable test case for it. It would require concurrent access to sass template that includes url helpers.

https://github.com/sass/sassc-rails/pull/148 might be an alternative, but I didn't test it by myself.

**Comment by ahorek** [comment]
closing this, because it seems to be resolved by a slightly alternative approach https://github.com/rails/sprockets/pull/759 .... after 3 years, ouch... :-(

**Pull request closed without merging**
