### PR TITLE
Remove extra new line after multi-line comments

### LINKED ISSUE #291: Sprockets inserts extra newlines when loading javascript asset
I have a javascript file that looks like this, named test.js:

```
/******/ function testRails() {
/******/ }
```

When that file goes through sprockets in development, it gets a newline after the first comment:

```
/******/
 function testRails() {
/******/ }
```

This is just a sample file but it looks like the files I get from Webpack.  I build up an app/assets/javascripts/bundle.js file from Webpack, and then include that file in application.js, so the webpack built JS goes into the standard Rails bundle.

The extra newlines are breaking the Webpack sourcemaps.  (Note that I'm talking about Webpack sourcemaps, not Sprockets source maps.)

I tried this on 4.0.0beta2 and 3.6.0, same behavior in both places.

Here is a short bit of ruby to reproduce, you need a file named 'test.js' that looks like my snippet above:

```
require 'sprockets'

e = Sprockets::Environment.new

e.append_path '.'
a = e.find_asset 'test.js'
puts a.source
```

### PR DESCRIPTION
**Pull request by repinel**
The following code should be processed and kept intact:

```javascript
/******/ function foo() {
}
```

However, a new line was being added before ` function`.

Fix #291

### CODE REVIEW

**Comment by michaelherold** [comment]
I tested this and it seems to fix the issue reported in issue 291.

From what I can tell, removing the extra newline shouldn't affect anything; however, just after the main change it ensures there's a newline after the body so I'm not totally sure. The header should just contain comments with directives, so there's nothing there that I think should cause an issue.

My only other comment is that the added test doesn't have quite the same format as the failing example given in the other issue. The original example was:

```js
/******/ function foo() {
/******/ }
```
I switched it up on my side and it still works as expected, but I thought I'd note it here.

**Comment by repinel** [comment]
@michaelherold Thanks for testing it! I didn't added the second comment because it didn't seem to add any value to the issue.

**Comment by schneems** [comment]
Seems good, thanks!

**Comment by repinel** [comment]
Cool 😄

**Pull request merged**
