### PR TITLE
Age param does not work

### PR DESCRIPTION
**Pull request by yoshiori**
I think that is a miss about refactoring

https://github.com/rails/sprockets/commit/b2ff6465a752f6f62b4e7e1d08407ce0c5e70c06

### CODE REVIEW

**Comment by matthewd** [comment]
Sounds like we're missing a test. Can you add one so this doesn't break again?

**Comment by yoshiori** [comment]
I have added a test.

**Comment by josh** [comment]
Good find.

Anyway the test could be written to avoid the additional timecop dependency?

**Comment by yoshiori** [comment]
OK, I fix it.

**Comment by josh** [comment]
:metal:

**Comment by yoshiori** [comment]
Thank you.

**Pull request merged**
