### PR TITLE
rm code to check unused exists

### PR DESCRIPTION
**Pull request by vipulnsward**
Followup on on https://github.com/rails/sprockets/pull/277#issuecomment-209551072

### CODE REVIEW

**Comment by rafaelfranca** [comment]
I don't get it. This code looks necessary to me. What keep track if the key existed before or not is in the `[]` method.

**Comment by schneems** [comment]
Ahh, i linked to the wrong delete in that issue.

**Comment by vipulnsward** [comment]
Looks like not used though? Or atleast not its usage is not covered by our tests.

**Comment by rafaelfranca** [comment]
Ah shit. that delete in `[]=` is also used. It is to change the order of the hash items and make the LRU logic work. We should put it back.

**Comment by vipulnsward** [comment]
Hmm, probably should be covered by specs as well.  Would you like me to work on it?

**Comment by schneems** [comment]
Yeah, we need some specs for it if possible

**Comment by vipulnsward** [comment]
All green now. Added specs specific to MemoryStore

**Comment by schneems** [comment]
Awesome, thanks!

**Comment by BlakeMesdag** [comment]
Ah, forgot about the LRU stuff. I've been unable to find a way to make any optimization that will still work with LRU unaffected.

Thanks for fixing this @vipulnsward & @rafaelfranca

**Pull request merged**
