### PR TITLE
update ruby versions

### PR DESCRIPTION
**Pull request by ahorek**
1/ add jruby build
2/ update ruby versions

### CODE REVIEW

**Comment by ahorek** [comment]
jruby build is stuck for some reason. I will investigate tomorrow.

**Comment by ahorek** [comment]
it was a travis bug, there're still some random failures on jruby (probably race conditions)

**Comment by rafaelfranca** [comment]
This is why we don't have jruby in the test suite. It is always broken. I'm fine with it in the allow-failures list. Can you move the stable version to there too?

**Comment by ahorek** [comment]
@rafaelfranca have you encountered this problem before? the build was successful, but then it hangs. Maybe the return status is wrong? I have no idea how to debug it.
```
Finished in 298.398660s, 2.8217 runs/s, 12.6978 assertions/s.
842 runs, 3789 assertions, 0 failures, 0 errors, 4 skips
You have skipped tests. Run with --verbose for details.
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

> Can you move the stable version to there too?

done, I've also moved 2.4, 2.5 in appveyor to allowed_failures untill https://github.com/rails/sprockets/pull/573 is fixed

**Comment by rafaelfranca** [comment]
I think that will resolve itself in the next build. I'll merge it as it is. Thanks.

**Pull request merged**
