### PR TITLE
Revert "Revert "ensure sassc tests are working properly""

### PR DESCRIPTION
**Pull request by schneems**
This reverts commit 0bb48ff938aa26d79c07d5b3b4bca9f19860d83d.

Windows test are failing, going to work on this code. Using appveyor to run tests on Windows

### CODE REVIEW

**Comment by guilleiguaran** [comment]
Are you going to include fixes for Windows in this PR or in a new one? 😊

**Comment by schneems** [comment]
Going to include fixes for windows on this PR, don't want master to be failing. 

Running tests on Appveyor is easier for now than me setting up a VM.

**Comment by schneems** [comment]
Two errors:

```  
1) Error:
TestSprocketsSassc#test_"@import css file from load path":
SassC::SyntaxError: Error: File to import not found or unreadable: compass
       Parent style sheet: C:/projects/sprockets/test/fixtures/sass/import_load_path.scss
        on line 1 of test/fixtures/sass/import_load_path.scss
>> @import "compass";
   ^
    C:/projects/sprockets/test/fixtures/sass/import_load_path.scss:1
    C:/Ruby22/lib/ruby/gems/2.2.0/gems/sassc-1.10.0/lib/sassc/engine.rb:46:in `render'
    C:/projects/sprockets/lib/sprockets/sassc_processor.rb:26:in `block in call'
    C:/projects/sprockets/lib/sprockets/utils.rb:137:in `module_include'
    C:/projects/sprockets/lib/sprockets/sassc_processor.rb:25:in `call'
    C:/projects/sprockets/lib/sprockets/processor_utils.rb:84:in `call_processor'
    C:/projects/sprockets/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
    C:/projects/sprockets/lib/sprockets/processor_utils.rb:65:in `reverse_each'
    C:/projects/sprockets/lib/sprockets/processor_utils.rb:65:in `call_processors'
    C:/projects/sprockets/lib/sprockets/processor_utils.rb:22:in `block in <class:CompositeProcessor>'
    C:/projects/sprockets/lib/sprockets/processor_utils.rb:33:in `call'
    C:/projects/sprockets/lib/sprockets/processor_utils.rb:33:in `call'
    C:/projects/sprockets/lib/sprockets/processor_utils.rb:84:in `call_processor'
    C:/projects/sprockets/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
    C:/projects/sprockets/lib/sprockets/processor_utils.rb:65:in `reverse_each'
    C:/projects/sprockets/lib/sprockets/processor_utils.rb:65:in `call_processors'
    C:/projects/sprockets/lib/sprockets/loader.rb:148:in `load_from_unloaded'
    C:/projects/sprockets/lib/sprockets/loader.rb:59:in `block in load'
    C:/projects/sprockets/lib/sprockets/loader.rb:324:in `fetch_asset_from_dependency_cache'
    C:/projects/sprockets/lib/sprockets/loader.rb:43:in `load'
    C:/projects/sprockets/lib/sprockets/cached_environment.rb:21:in `block in initialize'
    C:/projects/sprockets/lib/sprockets/cached_environment.rb:48:in `yield'
    C:/projects/sprockets/lib/sprockets/cached_environment.rb:48:in `load'
    C:/projects/sprockets/lib/sprockets/bundle.rb:24:in `block in call'
    C:/projects/sprockets/lib/sprockets/utils.rb:166:in `dfs'
    C:/projects/sprockets/lib/sprockets/bundle.rb:25:in `call'
    C:/projects/sprockets/lib/sprockets/processor_utils.rb:84:in `call_processor'
    C:/projects/sprockets/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
    C:/projects/sprockets/lib/sprockets/processor_utils.rb:65:in `reverse_each'
    C:/projects/sprockets/lib/sprockets/processor_utils.rb:65:in `call_processors'
    C:/projects/sprockets/lib/sprockets/loader.rb:148:in `load_from_unloaded'
    C:/projects/sprockets/lib/sprockets/loader.rb:59:in `block in load'
    C:/projects/sprockets/lib/sprockets/loader.rb:324:in `fetch_asset_from_dependency_cache'
    C:/projects/sprockets/lib/sprockets/loader.rb:43:in `load'
    C:/projects/sprockets/lib/sprockets/cached_environment.rb:21:in `block in initialize'
    C:/projects/sprockets/lib/sprockets/cached_environment.rb:48:in `yield'
    C:/projects/sprockets/lib/sprockets/cached_environment.rb:48:in `load'
    C:/projects/sprockets/lib/sprockets/base.rb:67:in `find_asset'
    C:/projects/sprockets/lib/sprockets/environment.rb:31:in `find_asset'
    C:/projects/sprockets/test/test_sassc.rb:80:in `block in render'
    C:/projects/sprockets/test/sprockets_test.rb:14:in `silence_warnings'
    C:/projects/sprockets/test/test_sassc.rb:79:in `render'
    C:/projects/sprockets/test/shared_sass_tests.rb:117:in `block in <module:SharedSassTestSprockets>'
```

And

```
  2) Error:
TestSasscFunctions#test_"@import css file from load path":
SassC::SyntaxError: Error: File to import not found or unreadable: compass
       Parent style sheet: C:/projects/sprockets/test/fixtures/sass/import_load_path.scss
        on line 1 of test/fixtures/sass/import_load_path.scss
>> @import "compass";
   ^
    C:/projects/sprockets/test/fixtures/sass/import_load_path.scss:1
    C:/Ruby22/lib/ruby/gems/2.2.0/gems/sassc-1.10.0/lib/sassc/engine.rb:46:in `render'
    C:/projects/sprockets/lib/sprockets/sassc_processor.rb:26:in `block in call'
    C:/projects/sprockets/lib/sprockets/utils.rb:137:in `module_include'
    C:/projects/sprockets/lib/sprockets/sassc_processor.rb:25:in `call'
    C:/projects/sprockets/lib/sprockets/processor_utils.rb:84:in `call_processor'
    C:/projects/sprockets/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
    C:/projects/sprockets/lib/sprockets/processor_utils.rb:65:in `reverse_each'
    C:/projects/sprockets/lib/sprockets/processor_utils.rb:65:in `call_processors'
    C:/projects/sprockets/lib/sprockets/processor_utils.rb:22:in `block in <class:CompositeProcessor>'
    C:/projects/sprockets/lib/sprockets/processor_utils.rb:33:in `call'
    C:/projects/sprockets/lib/sprockets/processor_utils.rb:33:in `call'
    C:/projects/sprockets/lib/sprockets/processor_utils.rb:84:in `call_processor'
    C:/projects/sprockets/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
    C:/projects/sprockets/lib/sprockets/processor_utils.rb:65:in `reverse_each'
    C:/projects/sprockets/lib/sprockets/processor_utils.rb:65:in `call_processors'
    C:/projects/sprockets/lib/sprockets/loader.rb:148:in `load_from_unloaded'
    C:/projects/sprockets/lib/sprockets/loader.rb:59:in `block in load'
    C:/projects/sprockets/lib/sprockets/loader.rb:324:in `fetch_asset_from_dependency_cache'
    C:/projects/sprockets/lib/sprockets/loader.rb:43:in `load'
    C:/projects/sprockets/lib/sprockets/cached_environment.rb:21:in `block in initialize'
    C:/projects/sprockets/lib/sprockets/cached_environment.rb:48:in `yield'
    C:/projects/sprockets/lib/sprockets/cached_environment.rb:48:in `load'
    C:/projects/sprockets/lib/sprockets/bundle.rb:24:in `block in call'
    C:/projects/sprockets/lib/sprockets/utils.rb:166:in `dfs'
    C:/projects/sprockets/lib/sprockets/bundle.rb:25:in `call'
    C:/projects/sprockets/lib/sprockets/processor_utils.rb:84:in `call_processor'
    C:/projects/sprockets/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
    C:/projects/sprockets/lib/sprockets/processor_utils.rb:65:in `reverse_each'
    C:/projects/sprockets/lib/sprockets/processor_utils.rb:65:in `call_processors'
    C:/projects/sprockets/lib/sprockets/loader.rb:148:in `load_from_unloaded'
    C:/projects/sprockets/lib/sprockets/loader.rb:59:in `block in load'
    C:/projects/sprockets/lib/sprockets/loader.rb:324:in `fetch_asset_from_dependency_cache'
    C:/projects/sprockets/lib/sprockets/loader.rb:43:in `load'
    C:/projects/sprockets/lib/sprockets/cached_environment.rb:21:in `block in initialize'
    C:/projects/sprockets/lib/sprockets/cached_environment.rb:48:in `yield'
    C:/projects/sprockets/lib/sprockets/cached_environment.rb:48:in `load'
    C:/projects/sprockets/lib/sprockets/base.rb:67:in `find_asset'
    C:/projects/sprockets/lib/sprockets/environment.rb:31:in `find_asset'
    C:/projects/sprockets/test/test_sassc.rb:80:in `block in render'
    C:/projects/sprockets/test/sprockets_test.rb:14:in `silence_warnings'
    C:/projects/sprockets/test/test_sassc.rb:79:in `render'
    C:/projects/sprockets/test/shared_sass_tests.rb:117:in `block in <module:SharedSassTestSprockets>'
820 runs, 3880 assertions, 0 failures, 2 errors, 6 skips
You have skipped tests. Run with --verbose for details.
rake aborted!
Command failed with status (1): [ruby -w -I"lib;test" -I"C:/Ruby22/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib" "C:/Ruby22/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb" "test/test*.rb" ]
```

**Comment by schneems** [comment]
The sassc-ruby gem does not work on windows. Looks like that needs to be fixed first.

**Comment by schneems** [comment]
I went ahead and added this into master, but skipped the windows tests. Need to get windows working still

**Pull request closed without merging**
