### PR TITLE
Parallel Compilation Spike

### PR DESCRIPTION
**Pull request by schneems**
This PR is not meant to be a final solution, more of a conversation starter.

Sprockets uses lots of disk IO, when it does this the GVL gets released and we can perform more work. Also sprockets is written to be very functional, each asset can be compiled in parallel without effecting another asset. 

This implementation of parallelization uses the directive processor, a directive is a comment in the head of a file telling sprockets to do something with another file:

```
//= require foo.js
//= require bar.js
```

In this implementation both `foo.js` and `bar.js` will be loaded in separate threads. If they have any directives in them, those will be run in separate threads. Since Sprockets 4 encourages use of a manifest file to declare what assets you want to be renderable, we use the `manifest.js` as a singular entry point, then each directive in it gets run in parallel. 

The "runner" works by performing the work designated in the original directive in a background thread, then we mutate any shared state such as `@directives` or `@links` synchronously via a `finish` block in order that they were created. 

This change will prefer apps who spend much of their time looking for and loading files. It will not speed up the mutation of files such as `sass => css`. In the future we could use this groundwork to run this work in "guilds" when they come out in a few years which will give us more speed.

The downsides of this approach: Significantly more code and the code is more complicated, we're creating more objects such as procs and arrays which takes up overhead, parallel compilation has greater ability to increase maximum memory use as more files are loaded into memory at the same time. Potentially harder to debug and reason about files being loaded in parallel. 

It also doesn't do anything to parallelize other asset directives such as Sass's `import` https://github.com/codetriage/codetriage/blob/master/app/assets/stylesheets/application.scss

In tests with codetriage, compilation happened 11% faster with this patch with very low standard deviation.

### CODE REVIEW

**Comment by camertron** [comment]
@schneems great to see some work being done to make asset precomp even faster! I did some work for my current company on this and came up with something that has decreased our precomp time from ~10 minutes to ~3 minutes. It uses the parallel gem to fork off a number of child processes, so assets are split up amongst the workers (4 in our case). The speed increase is proportional to the number of workers (CPU cores). Here's a [gist](https://gist.github.com/camertron/58ec20558e491fcd359bbb2f150191e6#file-parallel_sprockets-rb) you should be able to drop into a Rails app with Sprockets 3.7 and see a pretty instant speed-up. The number of workers is controlled by the `SPROCKETS_WORKER_COUNT` environment variable. Obviously this only works on *-nix systems that support `fork`, but we might be able to find a way to do it on Windows systems too (doesn't Windows have something similar called `spawn`?) We've been using this monkeypatch successfully in production for a couple of months with no issues so far.

Another optimization we added was asset "fingerprinting" where the precompile is skipped entirely if none of the assets have changed. It works by globbing all the files in `Rails.application.assets.paths` and throwing them through MD5 to produce a unique digest. The digest is compared between precompiles and skipped if the current digest is equal to the old one. This has also really cut down on the amount of time we spend waiting for asset precomp to finish. I remember reading such an improvement has already been made to Sprockets (right?) but it looks like Sprockets still has to actually compile an asset before it can calculate the asset's digest and thereby know if it has changed. Here's another [file](https://gist.github.com/camertron/58ec20558e491fcd359bbb2f150191e6#file-asset_fingerprinter-rb) in the same gist that represents the meat of the asset fingerprinting system we're using.

Thoughts?

**Comment by k0kubun** [comment]
I'm very excited to see this! I hope we'll have this on Sprockets 4.

> This change will prefer apps who spend much of their time looking for and loading files. It will not speed up the mutation of files such as sass => css. In the future we could use this groundwork to run this work in "guilds" when they come out in a few years which will give us more speed.

I've suffered from mostly for sass compiling and even compiling by libsass was slow without parallelization. I strongly want `Sprockets::Parallel::Fork`.

@schneems I guess it may take a while until Ruby 3 and "guilds" are released. In the meantime, how about allowing to use `fork` optionally? I think the existence of a class whose method calls `Kernel.#fork` won't break JRuby or etc.

**Comment by schneems** [comment]
@k0kubun sorry, missed this comment. I'm very hesitant to introduce threads here due to the nightmare it would cause in debugging thread unsafe extensions. Forking could be an option.

Going to close this for now.

**Comment by k0kubun** [comment]
no worries, I can understand your point too.

**Pull request closed without merging**
