### PR TITLE
FileStore: find caches and compute size only when needed

### PR DESCRIPTION
**Pull request by TimPetricola**
At the moment, `FileStore` finds all cache files to get the size at initialization. This operation can be heavy and is not necessarily needed.

As an example, `sprockets-rails` [always initializes](https://github.com/rails/sprockets-rails/blob/master/lib/sprockets/railtie.rb#L100-L104)  a `FileStore` and lets apps override it later:

```rb
module Sprockets
  class Railtie < ::Rails::Railtie
    config.assets.configure do |env|
      env.cache = Sprockets::Cache::FileStore.new(
        "#{env.root}/tmp/cache",
        config.assets.cache_limit,
        env.logger
      )
    end
  end
end
```

This PR moves size calculation out of `initialze` method to avoid this issue.

### CODE REVIEW

**Comment by TimPetricola** [comment]
@rafaelfranca Thanks a lot for merging! Do you know if there is a new release planned soon?

**Comment by jrafanie** [comment]
@rafaelfranca @schneems FYI, this cuts at least 0.5 second off of our rails boot time when applied to 3.6 with sprockets-rails 3.0.4.

Can this be backported for 3.6.x until there's a released 4.0 version?  Thanks in advance.

#### 3.6.0 without this change
```
03:43:09 ~/Code/manageiq (master) (2.2.4) + for x in 1 2 3 4 5; do; time bin/rails r 1; done
bin/rails r 1  7.00s user 1.74s system 99% cpu 8.791 total
bin/rails r 1  7.23s user 1.73s system 99% cpu 9.006 total
bin/rails r 1  6.96s user 1.75s system 99% cpu 8.755 total
bin/rails r 1  6.95s user 1.70s system 99% cpu 8.691 total
bin/rails r 1  7.07s user 1.75s system 99% cpu 8.863 total
```

#### 3.6.0 with this change
```
03:44:36 ~/Code/manageiq (master) (2.2.4) + for x in 1 2 3 4 5; do; time bin/rails r 1; done
bin/rails r 1  6.70s user 1.39s system 99% cpu 8.128 total
bin/rails r 1  6.83s user 1.42s system 99% cpu 8.305 total
bin/rails r 1  6.68s user 1.38s system 99% cpu 8.093 total
bin/rails r 1  6.76s user 1.42s system 99% cpu 8.225 total
bin/rails r 1  6.79s user 1.42s system 99% cpu 8.244 total
```

**Comment by jrafanie** [comment]
FYI, this also saves ~10 MB of memory for me... in addition to the 0.3 to 0.5 second speed boost booting rails:
https://gist.github.com/jrafanie/607ef1d44197a17c275e9d8f4d251dc2

**Comment by schneems** [comment]
Did someone submit a backport to 3.x branch?

**Comment by jrafanie** [comment]
@schneems Thanks.  I opened #307 to backport it to 3.x.  Let me know if you want a changelog or anything else.

**Comment by schneems** [comment]
#307 is merged

**Comment by jrafanie** [comment]
@TimPetricola 3.6.1 is released with your change backported.  👏

**Pull request merged**
