### PR TITLE
[Backport] Fixnum and Bignum are deprecated on Ruby trunk

### PR DESCRIPTION
**Pull request by maclover7**
This PR backports #392 to the `3.x` branch, which is still the default Sprockets release line used by Rails. This is one of the last code changes required to get Rails' test suite passing on Ruby v2.4.0-rc1. It would be amazing if a new release of Sprockets could be put out with this patch in it ❤️ ❤️ 

cc @schneems

### CODE REVIEW

**Comment by schneems** [comment]
Thanks! Can you add another commit to add 2.4 to the travis matrix for this branch?

**Comment by maclover7** [comment]
👍 updated @schneems, Travis is green

**Comment by schneems** [comment]
thanks!

**Comment by maclover7** [comment]
👍 no problem @schneems; is it possible to get this released in a v3.7.1 of Sprockets?

**Comment by schneems** [comment]
Done

**Pull request merged**
