### PR TITLE
Added Travis CI status in the README.

### PR DESCRIPTION
**Pull request by heliocola**
I created a Code Status section and I added the Travis badge into the README.
Before it was only available in the CONTRIBUTING.

I setup Codacy (https://www.codacy.com/app/heliocola/sprockets) and AppVeyor (https://ci.appveyor.com/project/rafaelfranca/sprockets) is already being used as well if you guys agree that it will add value.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Thank you but we keep these status badge out of the README for purpose. The build is supposed to be always green so users should not care about it. Only contributors needs.

**Comment by heliocola** [comment]
@rafaelfranca thanks for the information.
Do you think it worth adding this note into the README? That can very well prevent this to happen again in the future!
Thanks

**Comment by rafaelfranca** [comment]
I'm not sure. The readme is documentation for the users. We should not put any information about contributions there. We could put in the CONTRIBUTING.md file but I think this is already implicit since the travis badge is there.

**Comment by heliocola** [comment]
Got it thanks.

**Comment by schneems** [comment]
I think it provides value to show the actively tested/supported Ruby versions, there is one on rails/rails

**Comment by rafaelfranca** [comment]
We should not rely on third-party tools for that. If we want to show which versions are supported we should write in the README.

**Comment by heliocola** [comment]
@rafaelfranca I went of the gems you listed in your Sprockets talk and reviewed where the build status is located.
It is pretty much 50/50 between CONTRIBUTING and README.
I think it worth documenting it where this info is expected to be and document briefly the reason for that, but I understand this is something very low priority.

What do you think?
If you think it adds value I can open an issue so we can get the right explanation and after that send PR to a few other gems.

Summary:
README: 7/13
CONTRIBUTING: 6/13

Here is the list:
Rails: README (https://github.com/rails/rails/blob/master/README.md)
Spring: README (https://github.com/rails/spring/blob/master/README.md)
WebConsole: README (https://github.com/rails/web-console/blob/master/README.markdown)
sass-rails: README (https://github.com/rails/sass-rails/blob/master/README.md)
coffee-rails: README (https://github.com/rails/coffee-rails/blob/master/README.md)

Sprockets: CONTRIBUTING
ActiveResource: CONTRIBUTING (https://github.com/rails/activeresource/blob/master/CONTRIBUTING.md)
JQuery-Rails: CONTRIBUTING (https://github.com/rails/jquery-rails/blob/master/CONTRIBUTING.md)
JQuery-UJS: CONTRIBUTING (https://github.com/rails/jquery-ujs/blob/master/CONTRIBUTING.md)
Rails-HTML-Sanitizer: CONTRIBUTING (https://github.com/rails/rails-html-sanitizer/blob/master/CONTRIBUTING.md)
execjs: CONTRIBUTING (https://github.com/rails/execjs/blob/master/CONTRIBUTING.md)

Rails dependencies:
Bundler: README (https://github.com/bundler/bundler/blob/master/README.md)
Sprocket-Rails: README (https://github.com/rails/sprockets-rails/blob/master/README.md)


I looked at other popular gems and it is a split between README and CONTRIBUTING.

Thanks,
./Helio

**Pull request closed without merging**
