### PR TITLE
Remove duplicate "sprockets/loader" require

### PR DESCRIPTION
**Pull request by nettofarah**
Remove unnecessary `require 'sprockets/loader'`

### CODE REVIEW

**Comment by guilleiguaran** [comment]
As you can see the requires are ordered alphabetically, so it's a bit better to delete the one in [line 14](https://github.com/nettofarah/sprockets/blob/master/lib/sprockets/base.rb#L14) instead

**Comment by nettofarah** [comment]
Sounds good.. I'll do it

**Comment by nettofarah** [comment]
good :eyes:, @guilleiguaran.
I think we should be good now.

**Comment by guilleiguaran** [comment]
@nettofarah thank you very much!!!

**Pull request merged**
