### PR TITLE
Changes for frozen string literal compatibility

### PR DESCRIPTION
**Pull request by twalpole**

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Could you add the pragma comment too?

**Comment by twalpole** [comment]
@rafaelfranca Add the pragma comment to all the  files?  I've been testing with the --enable=frozen-string-literal RUBYOPT  and supplying PRs for a number of gems

**Comment by rafaelfranca** [comment]
> @rafaelfranca Add the pragma comment to all the files?

yes

**Comment by twalpole** [comment]
@rafaelfranca Just a quick clarification before I do this -- do you want the magic comment on ALL the ruby files -- or only the files that needed changes?

**Comment by rafaelfranca** [comment]
In all files.

**Comment by twalpole** [comment]
@rafaelfranca done. If you want me to squash let me know

**Comment by elia** [comment]
@twalpole any reason not to just `String.new` instead of `String.new("")`?

Also apparently `#dup` is slightly faster:

```rb
⤑ time ruby -e '20000000.times { String.new "a" }'                                                                                                                                                                                           ~
        5.66 real         5.64 user         0.01 sys
⤑ time ruby -e '20000000.times { "a".dup }'                                                                                                                                                                                                  ~
        5.06 real         5.02 user         0.02 sys
⤑ time ruby -e '20000000.times { +"a" }'                                                                                                                                                                                                     ~
        1.68 real         1.66 user         0.01 sys
⤑ time ruby --enable-frozen-string-literal -e '20000000.times { String.new "a" }'                                                                                                                                                            ~
        5.15 real         5.13 user         0.02 sys
⤑ time ruby --enable-frozen-string-literal -e '20000000.times { "a".dup }'                                                                                                                                                                   ~
        4.50 real         4.47 user         0.01 sys
⤑ time ruby --enable-frozen-string-literal -e '20000000.times { +"a" }'                                                                                                                                                                      ~
        1.83 real         1.81 user         0.01 sys
```

(too bad `+@` is a 2.3 only addition: https://bugs.ruby-lang.org/issues/11782)

**Comment by twalpole** [comment]
@elia   String.new and String.new("") produce strings with different encodings so I figured it was safer to go with the one that generated what would be created without frozen literals.  As for dup, it seems less immediately obvious when looking at the code why its being done, but I'm open to change to it if needed.

**Comment by schneems** [comment]
:clap: thanks for the work on this.

**Comment by elia** [comment]
another, promising, option would be to patch `String` adding `+@` on older rubies:

```rb
⤑ rvm 2.2.3                                                                                                                                                                                                                                  ~
⤑ time ruby -e 'class String; def +@; self; end; end; 20000000.times { +"a" }'                                                                                                                                                               ~
        2.55 real         2.54 user         0.01 sys
```

**Comment by schneems** [comment]
i'm :-1: on patching core classes from sprockets.

**Comment by twalpole** [comment]
Wouldn't that just return a frozen string anyway?

**Comment by elia** [comment]
@schneems agree that sprockets isn't the right place to "fix" older rubies, was just for the sake of #TMYK :)
@twalpole no, because you'd only define it on older rubies that don't support _--enable-frozen-string-literal_

**Comment by twalpole** [comment]
@elia good point :)

**Comment by twalpole** [comment]
@elia although older rubies do support frozen strings and it would be defined on them too, so it would need to check for frozen? and duplicate if they are    

   a = "test".freeze
   b = +a # b should be mutable

**Comment by elia** [comment]
@twalpole that's a good point too, in the sense that if anyone checks for the presence of that particular method on ruby < 2.3 and uses it on non-literal strings (that on older rubies are always mutable) they would get the wrong result.

Adding the check completely makes it not worth it:

```rb
⤑ time ruby -ve 'class String; def +@; frozen? ? self : dup; end; end; 20000000.times { +"a" }'                                                                                                                                              ~
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
        7.59 real         7.54 user         0.02 sys
```

**Comment by twalpole** [comment]
@elia your conditional is reversed - should be frozen? ? dup : self   -  but since we all agree sprockets is not the place to be patching core classes its irrelevant

**Comment by elia** [comment]
@twalpole right, but good catch, and here's the updated run, just for the record:

```rb
⤑ time ruby -ve 'class String; def +@; frozen? ? dup : self; end; end; 20000000.times { +"a" }'
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
        3.08 real         3.07 user         0.00 sys
```

**Pull request merged**
