### PR TITLE
Improved tests on Windows

### PR DESCRIPTION
**Pull request by daniel-rikowski**
Handles file uris, line endings and symlinks on Windows.

### CODE REVIEW

**Comment by schneems** [comment]
This is awesome. I owe you a pizza. Shoot me an email richard@heroku.com and i'll take it from there.

What's the story with symlinks on windows? It looks like they're supported http://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/  any idea why `File.symlink?` returns false on your machine?

**Comment by daniel-rikowski** [comment]
Symlinks on Windows are a NTFS-only feature. Perhaps that is why Git doesn't create actual symlinks on Windows, just text files with the symlink's target as content.

Note that this pull requests doesn't fix *all* test issues on Windows. Even before the latest changes to master, there was still one failing test. (At 6de1049bd2ff8562f0cc523fba3d48935e8e8ee8, now there are more)

Of course that might be a real bug, so I'll take another look at it during the weekend, perhaps I can track down the remaining Windows bug(s), too.

**Comment by daniel-rikowski** [comment]
I'll take another look at the symlinks, too. It looks like there might be a way: http://stackoverflow.com/a/19853853/23368

**Comment by daniel-rikowski** [comment]
I put no more effort into the symlink test, because there are a lot of restrictions on using them on Windows (Source: https://github.com/git-for-windows/git/wiki/Symbolic-Links) I don't think it's worth it at the moment.

**Comment by schneems** [comment]
Sounds good, you ready for this to be merged? Can you backport this to the 3.x branch?

**Comment by daniel-rikowski** [comment]
Yes, I have nothing more to add. 
I'll create a separate pull request for the backport (if that is ok)

**Comment by arthurnn** [comment]
I love it. :pizza: for both!
:beers:

**Comment by arthurnn** [comment]
Backported that to 3.x branch. 80d56207564b74b5456acf0b8db328987cbd5eb0

thanks again

**Comment by daniel-rikowski** [comment]
Thank you!

**Comment by schneems** [comment]
Sorry this fell off my "plate" so to speak. Thanks again! Let me know what you want on your pie.

**Pull request merged**
