### PR TITLE
consider files with the following extensions compressible: .ico .eot .otf .ttf

### PR DESCRIPTION
**Pull request by modosc**
these additions comes from [this list](https://www.fastly.com/blog/new-gzip-settings-and-deciding-what-compress)

i didn't add any font files to test with since they're usually huge and i don't know how to generate the font equivalent of a 1x1 gif. if you think it's necessary i could replace some of the empty files in `test/fixtures/octicons/` with the actual font files that i'd need to test each of the `COMPRESSABLE_MIME_TYPES`

### CODE REVIEW

**Comment by schneems** [comment]
Do browsers know how to uncompress gzipped webfonts?

**Comment by modosc** [comment]
seems like it:

https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/webfont-optimization?hl=en#reducing-font-size-with-compression

http://www.phpied.com/gzip-your-font-face-files/

**Comment by schneems** [comment]
I'm a little conflicted here and honestly out of my expertise level. I downloaded a `ttf` file and it looks like it is binary: https://www.dropbox.com/s/02t7w934rzm7784/OpenSans-Bold.ttf?dl=0 based off of my readings with gzip file service we shouldn't be zipping binary files, but those readings didn't go into depth as to why. Perhaps some binary files are already compressed as that fastly article mentions with `woff`. 

Based on the references you've provided, it is looking like compressing these files is the right thing to do. Can you change the constant from an array to a hash so that lookup time will be faster? After that I think it is safe to merge.

**Comment by modosc** [comment]
constant changed. do i need to do anything else to get this into 3.x?

**Comment by schneems** [comment]
I had no idea that `include?` was an alias for `key?` on a hash. We'll need to backport this to 3.x branch which I can do and cut a release. One last thing. I'm not seeing `x-icon` mentioned in the fastly post. Is that safe to compress?

**Comment by modosc** [comment]
it's listed as `image/vnd.microsoft.icon` in the fastly article but sprockets [uses a different mime type](https://github.com/rails/sprockets/blob/master/lib/sprockets.rb#L56)

    register_mime_type 'image/x-icon', extensions: ['.ico']

**Comment by schneems** [comment]
Great, thanks!

**Pull request merged**
