### PR TITLE
3.x 10x

### PR DESCRIPTION
**Pull request by janbiedermann**
PR to provide for #504 
See README.md

### CODE REVIEW

**Comment by schneems** [comment]
What ever happened to all these perf PRs? Are you still interested?

**Comment by janbiedermann** [comment]
Yes, i am interested in a fast asset solution for ruby-hyperloop. I am just not sure which direction sprockets will go, if this is a goal for sprockets to have fast compiles and maybe hot reload capability or if its just what it is. Then maybe its better for me to look somewhere else (what i currently tend to do). So what are the goals for sprockets?

**Comment by schneems** [comment]
Maintainable, stable, good errors, fast.

**Comment by janbiedermann** [comment]
so instead i created a opal-webpack-loader, provides more options in terms of asset processing

**Pull request closed without merging**
