### PR TITLE
Add small utility method for checking if a string is a file-digest uri

### PR DESCRIPTION
**Pull request by zach-taylor**
I was just diving into some of the Sprockets code for the first time and found this piece of logic in a few different places. So I thought this helper method was more semantically named and reduced some duplication. Not sure if it's in the right file though! I could use some feedback on the method's location and documentation.

Thanks!

### CODE REVIEW

**Comment by zach-taylor** [comment]
I noticed some similar code [here](https://github.com/rails/sprockets/blob/master/lib/sprockets/dependencies.rb#L61) but I don't know if it's a different string for a reason.

**Comment by schneems** [comment]
I think that last code would be fine with the same check. What do you think about the change @rafaelfranca ?

**Comment by schneems** [comment]
I think i'm going to close this for now. This is a bit of a refactoring and I want to mostly focus on performance and feature work for now until I get a better feel for Sprockets. Refactoring commits can make understanding history harder because blame gets muddled.

Thanks for the idea though. We might want to revisit this in the future. If you have any other ideas please let me know, i'm happy to have more people looking at and thinking about sprockets. Sorry for leaving this in limbo for so long.

**Comment by zach-taylor** [comment]
@schneems all good! Thanks for the update.

**Pull request closed without merging**
