### PR TITLE
Fix typo in code comment

### PR DESCRIPTION
**Pull request by tricknotes**

### CODE REVIEW

**Comment by prathamesh-sonpatki** [comment]
I think it's funny and we should keep it as is :smile:

**Comment by tricknotes** [comment]
Ah, right!
It's fantastic 💫

**Comment by rafaelfranca** [comment]
lol. It is funny but I don't see why not fix. I'll apply the patch manually.

**Comment by tricknotes** [comment]
I see. I reopened this PR.

**Pull request merged**
