### PR TITLE
Ruby 1.9.3 is EOL

### PR DESCRIPTION
**Pull request by tricknotes**

### CODE REVIEW

**Comment by matthewd** [comment]
If we're going to stop testing for it, we'd need to bump `required_ruby_version` too.

Obviously neither of those are appropriate in the 2.x branch... but here, in about-to-be-3.0... maybe?

**Comment by tricknotes** [comment]
> If we're going to stop testing for it, we'd need to bump `required_ruby_version` too.

Agreed. 9b2e61417a394df7a597db4f3d1bb1e01a029866

**Comment by rafaelfranca** [comment]
I think it is fine to drop support to Ruby 1.9 on this major release. @josh WDYT?

**Comment by josh** [comment]
I think we wanted to still support 1.9.3 on `3.x` (which is `master`) since we intended full Rails 4 compatibility there. Then on `4.x`, which targets Rails 5, we'll require Ruby 2 which is already the case: https://github.com/rails/sprockets/blob/4.x/sprockets.gemspec#L31

Previous discussion with @rafaelfranca https://github.com/sstephenson/sprockets/issues/603

**Comment by tricknotes** [comment]
Ah right.
Thanks, I missed this discussion.

**Pull request closed without merging**
