### PR TITLE
Fix sourcemap off lines

### PR DESCRIPTION
**Pull request by choihongil**
- Fix single line directive file cause source map off by one line, for example
   ```
   require foo
   ```
  
- ~~Ignore add missing semicolon with new line, refer to #419~~

- Insert semicolon after last none whitespace

### CODE REVIEW

**Comment by matthewd** [comment]
The semicolon is necessary: http://stackoverflow.com/a/1169596/476979

**Comment by choihongil** [comment]
exactly @matthewd. I revived semicolon insertion.

**Comment by marcusmalmberg** [comment]
Any news on this one?

**Comment by schneems** [comment]
Sorry about sleeping on this one. I Implemented the fixes in https://github.com/rails/sprockets/pull/515. Thanks for the pull request, I hope my extreme delay in reviewing this doesn't stop you from submitting a PR in the future.

**Pull request closed without merging**
