### PR TITLE
[close #440] Fix circular directives

### PR DESCRIPTION
**Pull request by schneems**
We de-couple the directive parsing and "resolving" from the "loading" so that a file does not have the ability to accidentally load itself when it is itself trying to load.

In the `DirectiveProcessor` we no longer run `load` instead we store the things we want to load on the asset metadata. Later we pull those things out and load them. Here's a tree representation of what's now happening for a `link` directive in `a.js` that points at an asset `b.js` that is "link"-ing to `a.js` (making a circular dependency):

- env.load("a.js") (pipeline=default)
  - env.load("a.js") (pipeline=source)
    - No processors for pipeline=source
    - Return pipeline=source
  - Processors for (pipeline=default): `[Bundle]`
    - env.load("a.js") (pipeline=self)
      - Processors for (pipeline=self): `[DirectiveProcessor]`
        - //= link b.js
          - b.s is added to `to_load` and `to_link` sets
      - pipeline=self asset returns
    - URIs pulled out of `to_load`, `to_link` sets and loaded
      - env.load("b.js") (pipeline=default)
        -  ...
        - return b.js (pipeline=default)
    - URIs pulled out of `required` set and loaded (existing behavior)
    - Merge required files to form top level asset
- Return top level asset

There is one concern here in that the extra `to_link` and `to_load` metadata gets stored in the cache for the `pipeline=self` asset. Also this asset would have traditionally have full URIs stored in the `links` metadata key, which can't be done yet because it expects fully expanded uris with digests. However, none of the tests fail, so I guess we're good? 

I think this is okay because we never actually use the file cache of `pipeline=self` (maybe?) instead we're always using the top level `pipeline=source` cache (I think). If that's the case we could save some processing overhead by not storing the same asset in the cache three different times. I honestly see no reason why this has to be recursive. It just makes the coder harder to reason about...but that's for a different PR/day.

### CODE REVIEW

**Comment by schneems** [comment]
Sigh, it works on my machine :shrug: Will have to investigate.

**Comment by schneems** [comment]
Travis cached a bad version of a gem, had to reset the cache and it's all green.

**Comment by merqlove** [comment]
Excellent, now it works like a Rocket 👍 Just dropped all caches after upgrade, otherwise i've seen `no method key?  for Array` error. in `source_map_utls.rb:127`

**Comment by merqlove** [comment]
Maybe it's because before upgrade i've had old caches for debug, but started server without debug. Nevermind 👍

**Comment by schneems** [comment]
Cool, If you have a repro of the failure can you open a new issue?

**Comment by merqlove** [comment]
I think it was just `old cache` problem. Tried same trick, but no error.

**Pull request merged**
