### PR TITLE
Fixnum and Bignum are now Integer in Ruby 2.4.0

### PR DESCRIPTION
**Pull request by schneems**
Preview was released today.

### CODE REVIEW

**Comment by schneems** [comment]
Okay, i'm not sure this patch is needed

```
$ irb
irb(main):001:0> { Integer => true }[1.class]
=> true
irb(main):002:0> { Fixnum => true }[1.class]
=> true
irb(main):003:0> 1.class == Fixnum
=> true
irb(main):004:0> 1.class == Bignum
=> true
irb(main):005:0> 1000000000000000000000000000000000000000000000000000000000000000.class == Bignum
=> true
```

However i'm not sure if we can rely on this behavior forever

**Comment by schneems** [comment]
If your app is caching any Bignum size integers than when you go from 2.3.0 to 2.4.0 the digests for intermediate cache i.e in `tmp/assets` will change regardless of if we explicitly bust the cache. I don't think the final file digests will change in this case because they should be digested as a string. In that case it sounds like we're better off risking the (highly unlikely) cache collision case.

**Comment by schneems** [comment]
This PR isn't required to get sprockets to work with 2.4.0 so i'm going to close it. I'm thinking we can change tests when Travis supports 2.4.0+.

**Comment by rafaelfranca** [comment]
Just to be clear the digest is only based on the content of the asset. What
was being discussed here is the sprockets cache key and this doesn't change
the file digest.

**Pull request closed without merging**
